- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "global"
  tasks:
  - name: Generate vpn certificate
    fortiosconfig:
     config: "vpn.certificate local"
     action: "delete"
     host:  "{{ host }}"
     username: "{{ username }}"
     password: "{{ password }}"
     vdom:  "{{ vdom }}"
     https: True
     config_parameters:
       name: "mycert"
